namespace Common.Enum
{
    public enum TypeOfSession
    {
        DOWNLOADING,
        SESSION_WITH_CENTRAL_SERVER,
        TOR_CONTROL_SESSION,
        UPDATING_OFFERING_FILES_SESSION_WITH_CENTRAL_SERVER,
        DOWNLOADING_OFFERING_FILES_SESSION_WITH_CENTRAL_SERVER
    }
}
