//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modeel {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34259")]
        public int File1Port1 {
            get {
                return ((int)(this["File1Port1"]));
            }
            set {
                this["File1Port1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34260")]
        public int File1Port2 {
            get {
                return ((int)(this["File1Port2"]));
            }
            set {
                this["File1Port2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2167737")]
        public long File2Size {
            get {
                return ((long)(this["File2Size"]));
            }
            set {
                this["File2Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34259")]
        public int File2Port1 {
            get {
                return ((int)(this["File2Port1"]));
            }
            set {
                this["File2Port1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4194304")]
        public long FlagSwitchCache {
            get {
                return ((long)(this["FlagSwitchCache"]));
            }
            set {
                this["FlagSwitchCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JohnWick.mkv")]
        public string File1Name {
            get {
                return ((string)(this["File1Name"]));
            }
            set {
                this["File1Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14651859537")]
        public long File1Size {
            get {
                return ((long)(this["File1Size"]));
            }
            set {
                this["File1Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SampleText.txt")]
        public string File2Name {
            get {
                return ((string)(this["File2Name"]));
            }
            set {
                this["File2Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PDF.pdf")]
        public string File3Name {
            get {
                return ((string)(this["File3Name"]));
            }
            set {
                this["File3Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3821115")]
        public int File3Size {
            get {
                return ((int)(this["File3Size"]));
            }
            set {
                this["File3Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34259")]
        public int File3Port1 {
            get {
                return ((int)(this["File3Port1"]));
            }
            set {
                this["File3Port1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34259")]
        public int File4Port1 {
            get {
                return ((int)(this["File4Port1"]));
            }
            set {
                this["File4Port1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.120")]
        public string File1IpAddress1 {
            get {
                return ((string)(this["File1IpAddress1"]));
            }
            set {
                this["File1IpAddress1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.120")]
        public string File1IpAddress2 {
            get {
                return ((string)(this["File1IpAddress2"]));
            }
            set {
                this["File1IpAddress2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.120")]
        public string File2IpAddress1 {
            get {
                return ((string)(this["File2IpAddress1"]));
            }
            set {
                this["File2IpAddress1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.120")]
        public string File3IpAddress1 {
            get {
                return ((string)(this["File3IpAddress1"]));
            }
            set {
                this["File3IpAddress1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TheOffice.mkv")]
        public string File4Name {
            get {
                return ((string)(this["File4Name"]));
            }
            set {
                this["File4Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("315069931")]
        public int File4Size {
            get {
                return ((int)(this["File4Size"]));
            }
            set {
                this["File4Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.120")]
        public string File4IpAddress1 {
            get {
                return ((string)(this["File4IpAddress1"]));
            }
            set {
                this["File4IpAddress1"] = value;
            }
        }
    }
}
